### ISSUE TITLE
Add Infro PR Checks?

### ISSUE THREAD

**Issue by colethienes** [shortlink-org/shortlink#13683]
I noticed that this repo uses Argo CD, and I thought I’d let you know that I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!

**Comment by batazor** [comment]
Hi. I do not plan to add any outside integrations with the cluster at this time.

In terms of feedback, based on the example:
- I think the conclusion is too noisy now, you can pass on the parts that haven't changed.
- It would be nice to add a documentation page on how to create a safe token
- It would be nice to open the source code of the client part so I don't have to worry about access to my cluster

Also, diff will also show argocd itself, I don't understand why I should see it in github when I can see it in the argocd UI.

Good luck with the development of the service!

**Comment by colethienes** [comment]
Thanks for the feedback!

> I think the conclusion is too noisy now, you can pass on the parts that haven't changed.

Yeah that makes sense.

> It would be nice to add a documentation page on how to create a safe token

Added this [here](https://infro.io/docs/register-argo-cd)!

> It would be nice to open the source code of the client part so I don't have to worry about access to my cluster

I think I will most likely do this! If I do, would it be most useful to you to open source a Github action or Github app?

>  I don't understand why I should see it in github when I can see it in the argocd UI.

You can also do this via `argocd app diff`! In my experience, developers rarely do this before merging though.

Cheers

**Comment by colethienes** [comment]
Open sourced it as a GitHub Action or self-hosted and added token configuration steps! https://github.com/infro-io/infro-core?tab=readme-ov-file#as-a-github-action
